spring:
  application:
    name: pantry-mvp
  datasource:
    url: jdbc:postgresql://localhost:5432/pantry
    username: pantry
    password: pantry
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
management:
  endpoints.web.exposure.include: "*"
